// This file is auto-generated by @hey-api/openapi-ts

export type Login = {
    username: string;
    password: string;
};

export type User = {
    userId: string;
    username: string;
    roles: Array<string>;
};

export type UserRequest = Login & {
    roles: Array<string>;
};

export type UpdatePassword = {
    password: {
        old: string;
        new: string;
    };
};

export type _Error = {
    error_code: string;
    error_message: string;
};

export type ErrorMessageObject = {
    error_code: string;
    error_message: {
        msg?: string;
    };
};

export type From = number;

export type Size = number;

export type GetPublicKeyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1.0/key';
};

export type GetPublicKeyResponses = {
    200: {
        key: string;
    };
};

export type GetPublicKeyResponse = GetPublicKeyResponses[keyof GetPublicKeyResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1.0/user';
};

export type GetUsersErrors = {
    401: _Error;
    403: _Error;
    500: _Error;
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
    200: {
        users: Array<User>;
    };
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type CreateUserData = {
    body?: UserRequest;
    path?: never;
    query?: never;
    url: '/v1.0/user';
};

export type CreateUserErrors = {
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    201: {
        userId: string;
    };
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type CreateTokenData = {
    body?: Login;
    path?: never;
    query?: never;
    url: '/v1.0/token';
};

export type CreateTokenErrors = {
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type CreateTokenError = CreateTokenErrors[keyof CreateTokenErrors];

export type CreateTokenResponses = {
    200: {
        token: string;
    };
};

export type CreateTokenResponse = CreateTokenResponses[keyof CreateTokenResponses];

export type UpdatePasswordData = {
    body?: UpdatePassword;
    path: {
        /**
         * User Id
         */
        userId: string;
    };
    query?: never;
    url: '/v1.0/user/{userId}/password';
};

export type UpdatePasswordErrors = {
    401: _Error;
    403: _Error;
    500: _Error;
};

export type UpdatePasswordError = UpdatePasswordErrors[keyof UpdatePasswordErrors];

export type UpdatePasswordResponses = {
    200: UpdatePassword;
};

export type UpdatePasswordResponse = UpdatePasswordResponses[keyof UpdatePasswordResponses];

export type AddRoleData = {
    body?: {
        role: string;
    };
    path: {
        /**
         * User Id
         */
        userId: string;
    };
    query?: never;
    url: '/v1.0/user/{userId}/role';
};

export type AddRoleErrors = {
    401: _Error;
    403: _Error;
    500: _Error;
};

export type AddRoleError = AddRoleErrors[keyof AddRoleErrors];

export type AddRoleResponses = {
    201: {
        role: string;
    };
};

export type AddRoleResponse = AddRoleResponses[keyof AddRoleResponses];

export type ClientOptions = {
    baseURL: 'https://api-ext.acme-local.online:22233/user' | 'http://localhost:22222/user' | 'https://{environment}.acme-local.online/user' | (string & {});
};